apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: group1-pod-netconfig
spec:
 subnet: subnet-0e1f237091c482a0e
 securityGroups:
 - sg-01b2f754593abea02
 - sg-0d92956a4663a339c
 
 
