apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::133150622354:role/eksctl-eksworkshop-eksctl-nodegro-NodeInstanceRole-57A75JJG1YCZ
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-16T00:12:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "892"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2de0a8cf-6b96-46a3-9a62-c947bd0d6d2c
data:
  mapUsers: |
    - userarn: arn:aws:iam::133150622354:user/rbac-user
      username: rbac-user
